### ISSUE TITLE
Capability to add Tone_Color to Tonnetz

### ISSUE THREAD

**Issue by thecreativecontrollab** [cifkao/tonnetz-viz#7]
![keyboard-color](https://user-images.githubusercontent.com/43919740/49428286-3a829d80-f76b-11e8-8199-4e5c36a972f5.jpg)
I'd like to see the individual colors of the notes; frequency colors. That way when visualizing the music using the tonnetz you would see the colors of the spectrum; scales, tones, and chords being used. 

I attempted to create a color scheme using the website however it only allows you to change the colors of the "Major & Minor" groups. This would only be 2 colors.   I believe each individual TONE_NAME can be assigned a TONE_COLOR  that would display on the face, maybe using a function or an array. I am new to coding and do not know how to add this to the existing code.

**Comment by cifkao** [comment]
This is interesting but I don't find it that useful and I wouldn't really be interested in adding it.

You are right that you cannot currently do this using the color schemes. If you want to try implementing it, you can start by having a look at this line: https://github.com/cifkao/tonnetz-viz/blob/be2a92a0cb768dfa74ce851b0cd641c77c5f7c5f/js/tonnetz.js#L357
Here you can change the fill colors of individual notes to your liking. Just create an array of color hex codes and if the state is `STATE_ON`, the index that array here using the `tone` variable.

I'm afraid this is all I can do to help you.
